### ISSUE TITLE
First phase task list

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#33]
This issue is for me to track the first phase of work.  This is brainstorming so that we have an initial list of stuff.

Here is a breakdown of tasks:

- [ ] Learn more about coachroachdb
- [ ] Learn more about the db helm chart
- [x] Find documentation for various configuration
- [ ] Learn more about the operator
- [ ] Test the operator and determine a baseline
- [x] Get the operator building
- [x] Determine if the project has CI/CD
- [ ] Get the tests for the operator working
- [ ] Openstack testing is one thing I am concerned about
- [ ] Fix headers in code to meet apache 2
- [ ] Document coding standard that this project is meeting

Administrative Items

- [x] Get Johns Github ID and start organizing the project in GitHub
- [x] Determine standup schedule
- [x] Get slack access
- [ ] cloud access
- [ ] Clean up Github issues a bit
- [ ] I need GitHub access to do stuff like add labels and such
- [x] Status of https://github.com/cockroachdb/cockroach-operator/pull/26

**Comment by chrislovecnm** [comment]
The helm chart is a good resource for what this operator needs to do. But what are the limitations for the helm chart?

**Comment by chrislovecnm** [comment]
Also, how do we match the CLI values against the cluster and how do you change values on a cluster without restarting nodes

**Comment by vladdy** [comment]
Welcome to the project, @chrislovecnm! Let me know if there is anything I can help with to get you up to speed.

**Comment by chrislovecnm** [comment]
@vladdy thanks!  Let me get my bearings and I would some feedback on some of the work you would like to see done with this project.  CRL was kind enough to agree to work together on this so that we can get a great product out for the community and their clients.
