### ISSUE TITLE
Testing meta-issue

### ISSUE THREAD

**Issue by udnay** [cockroachdb/cockroach-operator#612]
This is a master list of unit tests we should add to get better test coverage, specifically  negative tests.

**Decommission**
- [ ] Decommission if the resulting state is 3 or more nodes
- [ ] Gracefully handle decommission errors, do not alter cluster if decommission is in the process of happening

**Version Checker**
- [ ] Customer provided image is valid
  - [ ] Valid CRDB image
  - [ ] Customer can upgrade/downgrade 
- [ ]  Spins up container and runs `cockroach version`

**Partitioned Update**
- [ ] Downgrade to previous version
- [ ] Setting preserved downgrade
- [ ] Fail if we try to upgrade from oldest CRDB version to newest

**Cert Generation**
- [ ] Explicitly test an external cert
- [ ] Good e2e test coverage implicitly

**Comment by udnay** [comment]
@chrislovecnm @keith-mcclellan Here's the meta issue, I think a bunch of these are probably already covered, lets just confirm.

**Comment by chrislovecnm** [comment]
@keith-mcclellan what sql query do I run to determine if preserved is set? What is the testing criteria?

**Comment by keith-mcclellan** [comment]
we have to check that `cluster.preserve_downgrade_option` is set to the version we need to downgrade to.  The operator already sets this during the upgrade so it's just checking that it's still set before doing the downgrade.
